# Generated by Django 3.0 on 2020-07-01 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(choices=[('PRT', 'PRT'), ('TGT', 'TGT'), ('PGT', 'PGT')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='I', max_length=3)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('subject', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('present', models.IntegerField(default=0)),
                ('platform', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('homework', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('observation', models.CharField(blank=True, choices=[(' ', '-'), ('Needs Improvement', 'Needs Improvement'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent'), ('Outstanding', 'Outstanding')], max_length=20)),
                ('remark', models.CharField(blank=True, default='-', max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.Teacher')),
            ],
        ),
    ]
