# Generated by Django 3.0 on 2020-07-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.Teacher', verbose_name='Name of the Teacher'),
        ),
    ]
