# Generated by Django 3.0 on 2020-06-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='class_name',
            new_name='Class',
        ),
    ]
