# Generated by Django 3.0 on 2020-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20200701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Hindi', 'Hindi'), ('English', 'English'), ('Sanskrit', 'Sanskrit'), ('Science', 'Science'), ('Social Science', 'Social Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('CS', 'CS'), ('IP', 'IP'), ('Ph Education', 'Ph Education'), ('History', 'History'), ('Geography', 'Geography'), ('Sociology', 'Sociology'), ('Accountancy', 'Accountancy'), ('Business Studiies', 'Business Studies'), ('Economics', 'Economics'), ('EVS', 'EVS'), ('Drawing', 'Drawing'), ('Music', 'Music'), ('Games', 'Games'), ('Library', 'Library'), ('WE', 'WE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('PRT', 'PRT'), ('TGT', 'TGT'), ('PGT', 'PGT'), ('HM', 'HM'), ('VP', 'VP')], max_length=3),
        ),
    ]
