# Generated by Django 3.0 on 2020-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_auto_20200701_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('WhatsApp', 'WhatsApp'), ('MS Teams', 'MS Teams'), ('Zoom + WhatsApp', 'Zoom + WhatsApp'), ('Google Meet + WhatsApp', 'Google Meet + Whatsapp'), ('Other', 'Other')], max_length=30),
        ),
    ]
