# Generated by Django 3.0 on 2020-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20200701_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='observed_by',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
